version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      risc0-core:
        patterns:
          - "risc0-*"
        exclude-patterns:
          - "risc0-ethereum-trie"
      reth:
        patterns:
          - "reth*"
      alloy:
        patterns:
          - "alloy*"
      arkworks:
        patterns:
          - "ark-*"
